In [0]:

Ques 1. Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions

In [1]:
import numpy as np
import sys
import time
a=np.random.random((10,1))
print(a)
print("Mean is : ",a.mean())

[[0.9858548 ]
 [0.30563249]
 [0.91987466]
 [0.59886478]
 [0.84332703]
 [0.6839197 ]
 [0.17903303]
 [0.60165051]
 [0.7757577 ]
 [0.99599814]]
Mean is :  0.6889912842729256


In [0]:

Ques 2. Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

In [2]:
import numpy as np
import sys
import time
a=np.random.randint(0,30,(20,1))
print(a)
print("Variance of array is : ",a.var())
print("Standard Deviation is : ",a.std())

[[ 5]
 [17]
 [13]
 [ 4]
 [17]
 [ 6]
 [10]
 [ 9]
 [15]
 [17]
 [21]
 [18]
 [19]
 [ 2]
 [22]
 [ 8]
 [28]
 [28]
 [14]
 [27]]
Variance of array is :  59.5
Standard Deviation is :  7.713624310270756


In [0]:

Ques 3. Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.¶

In [3]:
import numpy as np
import sys
import time
a=np.random.randint(0,50,(10,20))
print("\nMatrix A is :\n",a)
b=np.random.randint(0,50,(20,25))
print("\n\nMatrix B is :\n",b)
c=np.matmul(a,b)
print("\n\nMultiplication of Two Matrices is: \n",c)
print("\n\n Sum of elements of new matrix is: ",c.sum())


Matrix A is :
 [[ 8  9 31 15 35  9 38 35 21 20 23  1 47  1  4 47 42 29 15  4]
 [25 16 15 23 46 49 36 31 45 37  8 28 28 36  4 30 23 31 43 42]
 [16 16 23 24  0 15 39 10 20 36 46 12 19 36 23 35 11 34 45 34]
 [ 1 27 35 34  0 25 28  3  2  3 31 47 43 18 36 16 48 26  0 13]
 [48  9 24 39 26 22 47 30 26 46 48 21 13 27 14 36 27 21 49 30]
 [36 29 45 24 35 23  5 27 48 49 43 31  2 42 41  1  2 18 18 37]
 [ 2 41 10  1 18  0 49 38  9 22  7  7 19 27  4 46 39 11 23 15]
 [ 6 36  7 37 27 20  9 49 48 49 32 32 15 11 10 20 11 21 28 41]
 [17  7 22 49 23 49  2 29 30  1 42  4 23 32 28 48 10  3 10 20]
 [ 1  2 23  4  4 32 10 14  3 20  0 44 39  5 48  5 33 16 40 47]]


Matrix B is :
 [[46  1 30  0  2  1 48 23 22 35 25 12 31 43 33 19  6  5 25 13 33 41 15 29
  36]
 [ 1  0 39 11  8 23 26 21 16 35 26 23 28 19 12 38 34 30 20 27 18 48  8 24
  17]
 [25 30 31 26 11 12 37 20  8 17 22 37  1 30 20 21 11 10  9 13 42 28 25 36
  49]
 [24 49 17 14 34 23 22 43 18 49 18 48 19 16 10 41 29 10  8 41 16 25 25 44
  32]
 [23  4 48 43 22

In [0]:

Ques4. Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A.¶

In [5]:
import numpy as np
import math

A=np.random.rand(10,1)
#print(A)
l=[]
for x in A:
  for y in x:
    B=1 / (1 + math.exp(-y))
    l.append(B)
print(l)

[0.7261178520801612, 0.536222040352943, 0.6211776716735549, 0.5629288738691429, 0.626117043231433, 0.5964068835515094, 0.562813122822367, 0.6540401478942587, 0.7113181164274572, 0.6831320878008142]
